version: '2'
services:
  bnetd:
    image: "quay.io/danfercf/ubuntu-16.10:0.1"
    network_mode: "host"
    container_name: bnetd
  ghost:
    image: "quay.io/danfercf/ghostbot:0.1"
    volumes: 
      - "/usr/local/ghost/maps:/usr/local/ghost/maps"
    network_mode: "host"
    depends_on:
       - "bnetd"
    container_name: ghost
