version: '2'
services:
  bnetd:
    image: "quay.io/danfercf/bnetd:0.1"
    volumes:
      - "/usr/local/pvpgn/etc:/usr/local/pvpgn/etc"
      - "/usr/local/pvpgn/log:/var/log/pvpgn"
      - "/usr/local/ghost/maps:/usr/local/pvpgn/maps"
    network_mode: "host"
    container_name: bnetd
